# Generated by Django 5.2.7 on 2025-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFilmTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("original_title", models.CharField(max_length=255)),
                ("video_id", models.CharField(blank=True, max_length=50, null=True)),
                ("source", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "title"],
            },
        ),
        migrations.DeleteModel(
            name="YTFilmTitle",
        ),
    ]
