# Generated by Django 5.2.7 on 2025-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                ("imdb_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "original_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "origin_country",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("popularity", models.FloatField(blank=True, null=True)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("vote_count", models.IntegerField(blank=True, null=True)),
                ("tagline", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
