# Generated by Django 5.2.7 on 2025-10-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
